project:
  type: website
  resources:
    - GSD_Calculator/**
    - pdfs/**

website:
  title: "Scarnecchia"
  site-url: "https://scarnecchia.net"
  reader-mode: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/scarnecchia
      - icon: twitter
        href: https://twitter.com/mountainherder

format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css



