baseurl: "/"
languageCode: "en-us"
title: "Daniel Scarnecchia"
theme: "hugo-prose"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 2

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: Search
      url: "#"
      identifier: menu-search
    - name: Subscribe
      url: "index.xml"
  footer:
    - name: Contact
      url: "/404.html"
      weight: 1
    - name: Categories
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: Tags
      url: "/tags/"
      weight: 3
      pre: "optional"
    - name: Suggest an edit
      url: "#"
      weight: 4
      identifier: "menu-edit"
    - name: Back to top
      url: "#"

params:
  homePosts: 6
  mainSections: ["post", "work"]
  editLink: "https://github.com/scarnecchia/website/edit/master/content/"
  authorDelimiter: " / "
  pageFeatures: [+sidenotes]
  description: >
    A website built through Hugo and blogdown with the hugo-prose theme.
  footer: >
    &copy; D. Scarnecchia
    2015–2021 CE

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
