---
title: "Double Chocolate Crinkle Cookies"
author: "D. Scarnecchia"
date: "2020-12-20"
categories: [dessert, cookies, christmas]
---

| *Prep Time*: 2 hours, 30 minutes
| *Cook Time*: 11 minutes
| *Total Time*: 2 hours, 45 minutes
| *Yield*: 20 cookies

## Ingredients

| Amount          | Ingredient                                      |
|-----------------|-------------------------------------------------|
| 125 g           | all-purpose flour (spoon & leveled)             |
| 53 g            | unsweetened natural cocoa powder                |
| 1 t             | baking soda                                     |
| ⅛ t             | salt                                            |
| 1 stick (115 g) | unsalted butter, softened to room temperature   |
| 100 g           | granulated sugar                                |
| 100 g           | packed light or dark brown sugar                |
| 1               | large egg at room temperature                   |
| 1 t             | pure vanilla extract                            |
| 180 g           | mini or regular size semi-sweet chocolate chips |

: Cookie Ingredients

| Amount | Ingredient           |
|--------|----------------------|
| 35 g   | granulated sugar     |
| 120 g  | confectioner's sugar |

: Sugar Coating

## Directions

1.  Whisk the flour, cocoa powder, baking soda, and salt together in a large bowl. Set aside.
2.  In a large bowl using a hand-held mixer or stand mixer fitted with a paddle attachment, beat the butter, granulated sugar, and brown sugar together on medium high speed until fluffy and creamed, about 2 minutes. Beat in egg and vanilla on high speed. Scrape down the sides and bottom of the bowl as needed.
3.  On low speed, slowly mix the dry ingredients into the wet ingredients until combined, then beat in the chocolate chips. The cookie dough will be thick and sticky. Cover dough tightly with aluminum foil or plastic wrap and chill for at least 2 hours and up to 3 days.[^1]
4.  Remove cookie dough from the refrigerator and allow to sit at room temperature for 15 minutes. You can preheat the oven during this time.
5.  Preheat oven to 350°F (177°C). Line two large baking sheets with parchment paper or silicone baking mats. Set aside.
6.  Scoop and roll balls of dough, about 1.5 Tablespoons of dough each, into balls. Roll each ball very lightly in granulated sugar, then generously in the confectioners' sugar. Place 3 inches apart on the baking sheets.
7.  Bake the cookies for 11-12 minutes. If the cookies aren't really spreading by minute 9, remove them from the oven and lightly bang the baking sheet on the counter 2-3x. This helps initiate that spread. Return to the oven for a couple more minutes. The cookies will be thick regardless, though---they deflate a little as they cool!
8.  Cool cookies for 5 minutes on the baking sheet, then transfer to a wire rack to cool completely.
9.  Cookies stay fresh covered at room temperature for up to 1 week.

[^1]: Chilling is absolutely necessary for this recipe.
