---
title: "Chocolate Layer Cookie (Mint Brownies)"
author: "D. Scarnecchia"
date: "2020-12-20"
categories: [dessert, brownies, christmas]
---

## Brownie Layer

### Ingredients

| Amount    | Ingredient            |
|-----------|-----------------------|
| 2 squares | Unsweetened chocolate |
| ½ C       | Butter                |
| 2         | Eggs                  |
| 1 C       | Sugar                 |
| ½ C       | Flour                 |

### Directions

1.  Preheat oven to 350 F.
2.  Grease Rectangular Pan
3.  Melt unsweetened chocolate and butter in a bain-marie
4.  Beat eggs and sugar until thick
5.  Add flour and chocolate mix and stir until smooth
6.  Pour batter into pan and bake for 25 minutes.

## Mint Cream Layer

### Ingredients

| Amount | Ingredient           |
|--------|----------------------|
| 1 ½ C  | Confectioner's sugar |
| 3 T    | Butter               |
| 2 T    | Heavy cream          |
| ¾ t    | Mint extract         |

### Directions

1.  Beat ingredients until smooth. Add green food coloring.

## Chocolate Glaze

### Ingredients

| Amount | Ingredient          |
|--------|---------------------|
| 2 oz   | Sweetened chocolate |
| 2 T    | Butter              |
| 1 t    | Vanilla extract     |

### Directions

1.  Melt chocolate and butter together in bain-marie
2.  Stir in vanilla

## Assembly

1.  Allow brownie layer to cool to room temperature
2.  Spread mint cream over brownie and chill for one hour
3.  After cooling, drizzle chocolate glaze over mint cream.
4.  Chill until firm
